---
apiVersion: cis.cattle.io/v1
kind: ClusterScanProfile
metadata:
  name: k3s-cis-1.9-profile
  annotations:
    clusterscanprofile.cis.cattle.io/builtin: "true"
spec:
  benchmarkVersion: k3s-cis-1.9
